services:
  nginx:
    build:
      context: ././.docker-compose/nginx
      dockerfile: dockerfile
    restart: unless-stopped
    ports:
      - "8090:80"
      - "450:443"
    volumes:
      - .:/var/www/html
      - ./.docker-compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel-network

  php:
    build:
      context: ./.docker-compose/php
      dockerfile: dockerfile
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - postgres
    networks:
      - laravel-network

  postgres:
    restart: unless-stopped
    image: postgres:latest
    ports:
      - "5555:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD:  ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB:  ${DB_DATABASE}
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - laravel-network

networks:
  laravel-network:

volumes:
  database:
    driver: local